# Generated by Django 3.2 on 2022-02-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Course Category')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCurricullum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='curricullum time')),
                ('viewed', models.IntegerField(default=0, editable=False)),
                ('video', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Course Curricullum',
                'verbose_name_plural': 'Courses Curricullum',
            },
        ),
        migrations.CreateModel(
            name='CourseDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded', models.IntegerField(default=0, editable=False)),
                ('title', models.CharField(max_length=50, verbose_name='curricullum time')),
                ('document', models.FileField(upload_to='course/document/', verbose_name='Documents')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecurricullum', verbose_name='curricullum document')),
            ],
            options={
                'verbose_name': 'Course Documents',
                'verbose_name_plural': 'Courses Documents',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='course/cover/', verbose_name='Course Cover')),
                ('video', models.CharField(max_length=200, verbose_name='Intro video')),
                ('cousername', models.CharField(max_length=50, verbose_name='Course Name')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
                ('introduction', models.TextField(verbose_name='Course Short Brief')),
                ('price', models.FloatField(verbose_name='Course price')),
                ('description', models.TextField(verbose_name='Course Full Description')),
                ('viewed', models.IntegerField(default=0, editable=False)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory', verbose_name='Course Category')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
