# Generated by Django 3.2 on 2022-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Course Category', 'verbose_name_plural': 'Courses Categories'},
        ),
        migrations.AddField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermididate', 'Intermididate'), ('Expert', 'Expert')], default='Beginner', max_length=50, verbose_name='Course Level'),
        ),
    ]
